import { FaPen, FaEtsy, FaBook, FaCuttlefish } from "react-icons/fa";
import { GoLogoGist } from "react-icons/go";

export const NOOPENER_NOREFERRER = "noopener,noreferrer";
export let links = [
	{
		key: "1",
		title: "Gist Github",
		description: "this description",
		cover: GoLogoGist,
		link: "https://gist.github.com/",
		enable: true,
	},
	{
		key: "2",
		title: "ProWritingAid",
		description: "this description",
		cover: FaPen,
		link: "https://prowritingaid.com/Free",
		enable: true,
	},
	{
		key: "3",
		title: "Grammarly",
		description: "this description",
		cover: FaBook,
		link: "https://app.grammarly.com/docs/new",
		enable: true,
	},
	{
		key: "4",
		title: "Hemingway Editor",
		description: "this description",
		cover: FaEtsy,
		link: "http://www.hemingwayapp.com/",
		enable: true,
	},
	{
		key: "5",
		title: "Carbon Now Sh",
		description: "this description",
		cover: FaCuttlefish,
		link: "https://carbon.now.sh/",
		enable: true,
	},
];

export const ROUTING_URLS = {
	home: "/home",
	about: "/about",
	all: "*",
};

export const tags = [
	"Art",
	"Artificial intelligence",
	"Blockchain",
	"Books",
	"Business",
	"Coronavirus",
	"Creativity",
	"Cryptocurrency",
	"Culture",
	"Data science",
	"Design",
	"Education",
	"Entrepreneurship",
	"Family",
	"Fiction",
	"Food",
	"Health",
	"Humor",
	"Innovation",
	"Javascript",
	"Leadership",
	"Life",
	"Life lessons",
	"Love",
	"Mental health",
	"Music",
	"Mysql",
	"Photography",
	"Poetry",
	"Politics",
	"Postgresql",
	"Productivity",
	"Programming",
	"Psychology",
	"Relationships",
	"Self",
	"Self improvement",
	"Social media",
	"Software development",
	"Sports",
	"Startup",
	"Technology",
	"Travel",
	"Ux",
	"Work",
	"Writing",
	"Docker",
	"Software engineering",
];
